[2025-01-11T00:21:29.703+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T00:21:29.706+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-11T00:21:27.517177+00:00 [queued]>
[2025-01-11T00:21:29.709+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-11T00:21:27.517177+00:00 [queued]>
[2025-01-11T00:21:29.709+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T00:21:29.716+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): france_travail_data_extraction> on 2025-01-11 00:21:27.517177+00:00
[2025-01-11T00:21:29.720+0000] {standard_task_runner.py:72} INFO - Started process 71677 to run task
[2025-01-11T00:21:29.721+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'france_travail_data_extraction', 'manual__2025-01-11T00:21:27.517177+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/job_market_dag.py', '--cfg-path', '/tmp/tmp1v7bn9v9']
[2025-01-11T00:21:29.722+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask france_travail_data_extraction
[2025-01-11T00:21:29.743+0000] {task_command.py:467} INFO - Running <TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-11T00:21:27.517177+00:00 [running]> on host bun
[2025-01-11T00:21:29.774+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='data_processing' AIRFLOW_CTX_TASK_ID='france_travail_data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T00:21:27.517177+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-11T00:21:27.517177+00:00'
[2025-01-11T00:21:29.775+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-11T00:21:29.775+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-11T00:21:29.775+0000] {logging_mixin.py:190} INFO - Current task name:france_travail_data_extraction state:running start_date:2025-01-11 00:21:29.707069+00:00
[2025-01-11T00:21:29.776+0000] {logging_mixin.py:190} INFO - Dag name:data_processing and current dag run status:running
[2025-01-11T00:21:29.776+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T00:21:29.805+0000] {docker.py:345} INFO - Starting docker container from image aurel_extract_dock:v3
[2025-01-11T00:22:55.851+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-01-11T00:22:55.854+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-11T00:22:55.857+0000] {process_utils.py:132} INFO - Sending 15 to group 71677. PIDs of all processes in the group: [71677]
[2025-01-11T00:22:55.857+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 71677
[2025-01-11T00:22:55.863+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-11T00:22:55.875+0000] {docker.py:505} INFO - Stopping docker container
[2025-01-11T00:23:06.173+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T00:23:06.212+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=71677, status='terminated', exitcode=0, started='00:21:29') (71677) terminated with exit code 0
